---
title: "Workflowr page from the catchSalmon/catchKallisto paper"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This website hosts the code for the transcript-level differential expression paper, which presents the methodology implemented in the functions `catchSalmon` and `catchKallisto` from the R/Bioconductor package [edgeR](https://bioconductor.org/packages/release/bioc/html/edgeR.html).

## Simulation study

The pages below present the necessary steps to rerun our simulation study and the code used to generate the figures and tables from the main and supplementary texts of the transcript-level differential expression paper.

* [Rerunning the simulation study](simulation-howto.html)
* [Complete report (results presented in the supplementary materials)](simulation-complete.html)
* [Reduced report (results presented in the main paper)](simulation-paper.html)
  
## Case study

The pages below present the data pre-processing steps and analysis report of the RNA-seq experiments from the human cancer cell lines H1975 and HCC827 (GEO accession [GSE172421](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE172421) and [GSE86337](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE86337)).

* [Data pre-processing](casestudy-howto.html)
* [Analysis report](casestudy.html)
