---
title: "Simulation - Rerunning the simulation study"
author: "Pedro Baldoni"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

The R code used in our simulation study to generate the simulated data, quantify the FASTQ files, run DTE methods, and summarize the results was organized as an R package and it is located in the GitHub repository of this page in the directory `./code/pkg`.

To run our simulations, users should refer to the files stored in the directory `./code/simulation`. The text file `./code/simulation/readme.txt` presents the necessary steps to run the simulations and summarize the results, which can be briefly summarized as:

1. Run the file `parameters.R` with, for example, the command `Rscript parameters.R`.

2. Run the SLURM script `run.sh` with, for example, `sbatch run.sh` on your HPC running the SLURM workload manager. If your HPC uses a different workload manager, please change `run.sh` accordingly.

3. Once all simulations have been completed, run the script `summarize.R` with, for example, the command `Rscript summarize.R` to summarize all the results.

Once steps 1-3 above have been completed, the Rmarkdown `simulation-*.Rmd` files under `./analysis` can be run.
